<!doctype html>
<html class="no-js" lang="en">
    <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <title>Terms &amp; Conditions - Virtus Nutra</title>
        <meta name="viewport" content="width=device-width, height=device-height"/>
        <link href="css/global.css" rel="stylesheet" />
        <link href="css/site_page-52.css" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
        <script type="text/javascript" src="js/jquery-1.11.0.min.js"></script>
        <script type="text/javascript" src="js/jquery-migrate-1.2.1.min.js"></script>
        <script type="text/javascript" src="js/jquery-ui-1.11.2.min.js"></script>
        <script type="text/javascript" src="js/modernizr-2.8.3.min.js"></script>
    </head>

    <body class="retail">
        <div class="page_container">
            <input type="hidden" id="shopping_cart_num" value="0">
            <?php include('header.php') ?>
            <section class="terms-header wrapper"> <strong>Terms &amp; Conditions</strong> </section>
            <section class="terms">
                <div class="wrapper">
                    <h1>Virtus Nutra Fitness Program - Terms of Offer</h1>
                    <p> <a href="#health-disclaimer">Health Disclaimer</a><br>
                        <a href="#vip-membership">VIP Membership Program</a><br>
                        <a href="#vip-returns">Return Policy for VIP Membership Deliveries</a><br>
                        <a href="#standard-returns">Return Policy for Standard Deliveries</a><br>
                        <a href="#using-website">Using the Website</a><br>
                        <a href="#your-content">Your Content</a><br>
                        <a href="#information-accuracy">Accuracy of Information</a><br>
                        <a href="#sales-tax">Sales Tax</a><br>
                        <a href="#fraud">Fraud</a><br>
                        <a href="#intellectual-property">Intellectual Property Rights</a><br>
                        <a href="#third-party">Third Party Websites</a><br>
                        <a href="#linking-framing">Linking and Framing</a><br>
                        <a href="#comments">Comments</a><br>
                        <a href="#indemnification">Indemnification</a><br>
                        <a href="#disclaimers-exclusions-limitations">Disclaimers, Exclusions and Limitations</a><br>
                        <a href="#force-majeure">Force Majeure</a><br>
                        <a href="#domestic-use-export-restrictions">Domestic Use and Export Restrictions</a><br>
                        <a href="#arbitration">Arbitration</a><br>
                        <a href="#modification-of-terms">Modification of Terms of Service</a><br>
                        <a href="#termination">Termination</a><br>
                        <a href="#integration">Integration</a><br>
                        <a href="#additional-terms">Additional Terms</a><br>
                    </p>
                    <p>By placing an order through this website, you agree to the terms and conditions set forth below. Please read through these terms and conditions carefully before placing your order, and print a copy for future reference. Please also read our Privacy Policy regarding personal information provided by you, which is incorporated herein by reference.</p>
                    <p id="health-disclaimer"><strong>Health Disclaimer</strong></p>
                    <p>The statements made on this website, as well as any materials or supplements distributed or sold on <a href="#" target="_blank"><u>VirtusNutra.com</u></a>, have not been evaluated by the Food and Drug Administration. Virtus Nutra products are not intended to diagnose, treat, cure, or prevent any disease. If you are pregnant, nursing, taking medication, or have a history of heart conditions, we suggest consulting with a healthcare professional before using any of our products. The results achieved with all products are not typical, and not everyone will experience these results. <br>
                    </p>
                    <p><strong>How Does the VIP Membership Offer Work?</strong></p>
                    <p>A. You must pay a shipping and handling fee of $4.99 USD for us to send you a 14-day trial supply of Virtus Nutra. We ship the product the day after you place your order (with the exception that orders placed Friday-Sunday will be shipped the following Monday). We allow up to 4 days for you to receive the trial supply. Thus, in order for you to have 14 days to try the product, we consider the end date for your trial period to be 18 days after you place your order, which is 14 days plus 4 days for processing and transit.</p>
                    <p>B. If you do not call customer service to cancel within 18 days of ordering your free trial, you will continue with our VIP Membership Program. See details below.</p>
                    <p id="vip-membership"><strong>VIP Membership Program</strong></p>
                    <p>Unless you cancel before the end of your trial period as specified above, we will ship your first 30-day supply of Virtus Nutra at the end of your trial period. Thereafter, you will continue to receive a fresh 30-day supply of Virtus Nutra each month for as long as you remain a member of our VIP Membership Program. The credit card you provided when you ordered the trial product will be automatically charged $74.98 (plus tax if applicable) when each new monthly supply ships. To cancel future shipments, you must call 1-877-204-3263 at least 1 day prior to the date that your next monthly delivery ships. Customers located in Guam, Puerto Rico, and the Virgin Islands, please call us at +1 (877) 301-6149. Customers in Australia, please call us at 1800-084-649. Our customer service center is open Mon-Thurs: 8am - 9pm Eastern Time (US), Fri: 8am - 6pm Eastern Time (US), Sat: 9am - 6pm Eastern Time (US), and Sun: 11am - 5pm Eastern Time (US).</p>
                    <h2>The Virtus Nutra Guarantee:</h2>
                    <p id="vip-returns"><strong>Return Policy for VIP Membership Deliveries</strong></p>
                    <p>Virtus Nutra, LLC retains a total guarantee of customer satisfaction on all Virtus Nutra VIP Membership products. If you, the buyer, are unhappy with the product for any reason — even if you've used the full supply of the supplement — you can return the remaining supply or empty bottle for a full refund of the purchase price minus shipping and handling. To obtain your refund in the United States and Canada, call us at 1-877-204-3263 Mon-Thurs: 8am - 9pm Eastern Time (US), Fri: 8am - 6pm Eastern Time (US), Sat: 9am - 6pm Eastern Time (US), and Sun: 11am - 5pm Eastern Time (US). Customers located in Guam, Puerto Rico, and the Virgin Islands, please call us at +1 (877) 301-6149. Customers in Australia, please call us at 1800-084-649. Customers in the United Kingdom, please call us at 0808-1012202. You will be given a Return Merchandise Authorization (RMA) number. To receive your refund, your return must be received at our shipping facility within 30 days of purchase. Be sure to clearly write the return merchandise authorization (RMA) number on the outside of the box. Our shipping department is NOT allowed to accept any packages without an RMA number. You pay for return shipping.</p>
                    <p>Please send your package to the appropriate facility:</p>
                    <ul>
                        <li>
                            <p>In the United States: Virtus Nutra, 105 Commerce Dr, Aston, PA 19014.</p>
                        </li>
                        <li>
                            <p>In Canada: Virtus Nutra Returns, P.O. Box 1051, Fort Erie ON L2A 6C7.</p>
                        </li>
                        <li>
                            <p>In Australia: Virtus Nutra, PO Box 535, Braeside VIC 3195.</p>
                        </li>
                        <li>
                            <p>In the United Kingdom: Virtus Nutra Returns, PO Box 1417, Bedfordshire, MK41 0QB.</p>
                        </li>
                    </ul>
                    <p>We will not accept or issue a refund for any packages marked "return to sender" or refused that do not include a valid RMA number. If you return a package, we recommend that you obtain proof of shipment. Upon receipt of your returned product with a valid RMA number, a refund will be issued to your credit card. After the shipping department receives your return, it generally takes 3-5 business days or less to process your refund. Once a return is processed, it can take up to one billing cycle for this return to be posted to your account, depending on your credit card company or financial institution.</p>
                    <p id="standard-returns"><strong>Return Policy for Standard Deliveries</strong></p>
                    <p>To be considered for reimbursement, products purchased through standard delivery (all non-VIP Membership purchased products) must be unopened and in the original packaging. To return a product, you must do the following: In the United States and Canada call us at 1-877-204-3263, Mon-Thurs: 8am - 9pm Eastern Time (US), Fri: 8am - 6pm Eastern Time (US), Sat: 9am - 6pm Eastern Time (US), and Sun: 11am - 5pm Eastern Time (US), within 30 days of purchase. Customers located in Guam, Puerto Rico, and the Virgin Islands, please call us at +1 (877) 301-6149. Customers in Australia, please call us at 1800-084-649. Customers in the United Kingdom, please call us at 0808-1012202. You will be given a Return Merchandise Authorization (RMA) number. To receive a refund, you must postmark your return within 30 days of purchase. Be sure to clearly write the return merchandise authorization (RMA) number on the outside of the box. Our shipping department is NOT allowed to accept any packages without an RMA number. You pay for return shipping.</p>
                    <p>Please send your package to the appropriate facility:</p>
                    <ul>
                        <li>
                            <p>In the United States: Virtus Nutra, 105 Commerce Dr, Aston, PA 19014.</p>
                        </li>
                        <li>
                            <p>In Canada: Virtus Nutra Returns, P.O. Box 1051, Fort Erie ON L2A 6C7.</p>
                        </li>
                        <li>
                            <p>In Australia: Virtus Nutra, PO Box 535, Braeside VIC 3195.</p>
                        </li>
                        <li>
                            <p>In the United Kingdom: Virtus Nutra Returns, PO Box 1417, Bedfordshire, MK41 0QB.</p>
                        </li>
                    </ul>
                    <p>We will not accept or issue a refund for any packages marked "return to sender" or refused that do not include a valid RMA number. If you return a package, we recommend that you obtain proof of shipment. Upon receipt of your returned product with a valid RMA number, a refund will be issued to your credit card. After the shipping department receives your return, it generally takes 3-5 business days or less to process your refund. Once a return is processed, it can take up to one billing cycle for this return to be posted to your account, depending on your credit card company or financial institution.</p>
                    <h2>TERMS OF SERVICE</h2>
                    <p>This Terms of Service ("TOS") is a legally binding agreement made by and between Virtus Nutra, LLC ("we" or "us") and you, personally and, if applicable, on behalf of the entity for whom you are using this website (collectively, "you"). This TOS governs your use of the VirtusNutra.com website ("Website") and the services we offer on the Website ("Services"), so please read it carefully.</p>
                    <p><strong>BY ACCESSING OR USING ANY PART OF THE WEBSITE, YOU AGREE THAT YOU HAVE READ, UNDERSTAND, AND AGREE TO BE BOUND BY THIS TOS. IF YOU DO NOT AGREE TO BE SO BOUND, DO NOT ACCESS OR USE THE WEBSITE.</strong></p>
                    <p><strong>INTERNET TECHNOLOGY AND THE APPLICABLE LAWS, RULES, AND REGULATIONS CHANGE FREQUENTLY. ACCORDINGLY, WE RESERVE THE RIGHT TO MAKE CHANGES TO THIS TOS AT ANY TIME. YOUR CONTINUED USE OF THE WEBSITE CONSTITUTES ASSENT TO ANY NEW OR MODIFIED PROVISION OF THIS TOS THAT MAY BE POSTED ON THE WEBSITE.</strong></p>
                    <p><strong>THIS AGREEMENT CONTAINS ARBITRATION AND CLASS ACTION WAIVER PROVISIONS THAT WAIVE YOUR RIGHT TO A COURT HEARING OR JURY TRIAL OR TO PARTICIPATE IN A CLASS ACTION. ARBITRATION IS MANDATORY AND IS THE EXCLUSIVE REMEDY FOR ANY AND ALL DISPUTES.</strong></p>
                    <p id="using-website">1. <strong>Using the Website.</strong></p>
                    <p>(a) Eligibility. Except as expressly provided below, Services may only be used by, and Membership is limited to, individuals who can form legally binding contracts under applicable law. Without limitation, minors are prohibited from becoming Members and, except as specifically provided below, using fee-based Services. Membership is defined by engaging in a purchase agreement with Virtus Nutra, LLC wherein you, the consumer, purchase one of the products found on the Website.</p>
                    <p>(b) Compliance. You must comply with all of the terms and conditions of this TOS, the policies referred to below, and all applicable laws, regulations, and rules when you use the Website.</p>
                    <p>(c) License and Restrictions. Subject to the terms and conditions of this TOS, you are hereby granted a limited, non-exclusive right to use the content and materials on the Website. You may not use any third-party intellectual property without the express written permission of the applicable third party, except as permitted by law. The Website will retain ownership of its intellectual property rights, and you may not obtain any rights therein by virtue of this TOS or otherwise, except as expressly set forth in this TOS. You will have no right to use, copy, display, perform, create derivative works from, distribute, have distributed, transmit, or sublicense from materials or content available on the Website, except as expressly set forth in this TOS. You may not attempt to reverse engineer any of the technology used to provide the Services.</p>
                    <p>(d) Prohibited Conduct. In your use of the Website and the Services, you may not: (i) infringe any patent, trademark, trade secret, copyright, right of publicity, or other right of any party; (ii) defame, abuse, harass, stalk any individual, or disrupt or interfere with the security or use of the Services, the Website, or any websites linked to the Website; (iii) interfere with or damage the Website or Services, including, without limitation, through the use of viruses, cancel bots, Trojan horses, harmful code, flood pings, denial-of-service attacks, packet or IP spoofing, forged routing of electronic mail address information, or similar methods or technology; (iv) attempt to use another user's account, impersonate another person or entity, misrepresent your affiliation with a person or entity, including, without limitation, the Website, or create or use a false identity; (v) attempt to obtain unauthorized access to the Website or portions of the Website that are restricted from general access; (vi) engage, directly or indirectly, in transmission of "spam," chain letters, junk mail, or any other type of unsolicited solicitation; (vii) collect, manually or through an automatic process, information about other users without their express consent or other information relating to the Website or the Services; (viii) use any meta tags or any other "hidden text" utilizing the Virtus Nutra name, trademarks, or product names; (ix) advertise, offer to sell, or sell any goods or services, except as expressly permitted by the Website; (x) engage in any activity that interferes with any third party’s ability to use or enjoy the Website or Services; or (xi) assist any third party in engaging in any activity prohibited by this TOS.</p>
                    <p>(e) Other Users. If you become aware of any conduct that violates this TOS, we encourage you to contact Customer Service. We reserve the right, but will have no obligation, to respond to such communications.</p>
                    <p id="your-content">2. <strong>Your Content.</strong></p>
                    <p>(a) License. By posting, storing, or transmitting any content on or to the Website, you hereby grant us a perpetual, worldwide, non-exclusive, royalty-free, sub-licensable right and license to use, copy, display, perform, create derivative works from, distribute, have distributed, transmit, and sublicense such content in any form, in all media now known or hereinafter created, anywhere in the world. You hereby irrevocably waive any claims based on moral rights or similar theories, if any.</p>
                    <p>(b) Objectionable Content. We do not have the ability to control the nature of the user-generated content offered through the Website. You are solely responsible for your interactions with other users of the Website and any content that you post. We will not be liable for any damage or harm resulting from any content, nor from your interactions with other users of the Website. We reserve the right, but have no obligation, to monitor interactions between you and other users of the Website and take any other action to restrict access to or the availability of any material that we or another user of the Website may consider to be obscene, lewd, lascivious, filthy, excessively violent, harassing, or otherwise objectionable (including, without limitation, because it violates this TOS).</p>
                    <p id="information-accuracy">3. <strong>Accuracy of Information.</strong></p>
                    <p>We attempt to ensure that the information on the Website is complete and accurate; however, this information may contain typographical errors, pricing errors, and other errors or inaccuracies. We assume no responsibility for such errors and omissions, and reserve the right to: (i) revoke any offer stated on the Website at any time; (ii) correct any errors, inaccuracies, or omissions; and (iii) make changes to prices, content, promotions, product descriptions or specifications, or other information on the Website at any time.</p>
                    <p id="sales-tax">4. <strong>Sales Tax.</strong></p>
                    <p>If you purchase any products available on the Website ("Products"), you will be responsible for paying any applicable sales tax indicated on the Website.</p>
                    <p id="fraud">5. <strong>Fraud.</strong></p>
                    <p>We reserve the right, but undertake no obligation, to actively report and prosecute actual and suspected credit card fraud. We may, in our discretion, require further authorization, such as a telephone confirmation of your order and other information, from you. We reserve the right to cancel, delay, refuse to ship, or recall from the shipper any order if fraud is suspected. We capture certain information during the order process, including time, date, IP address, and other information that will be used to locate and identify individuals committing fraud. If any Website order is suspected to be fraudulent, we reserve the right, but undertake no obligation, to submit all records, with or without a subpoena, to all law enforcement agencies, the credit card company, and any relevant financial institutions for fraud investigation. We reserve the right to cooperate with authorities to prosecute offenders to the fullest extent of the law.</p>
                    <p id="intellectual-property">6. <strong>Intellectual Property Rights. </strong></p>
                    <p>(a) Copyright. All materials on the Website, including, without limitation, the logos, design, text, graphics, other files, and the selection and arrangement thereof are either owned by us or are the property of our suppliers, licensors, or other companies. You may not use such materials without express written permission.</p>
                    <p>(b) Trademarks. Virtus Nutra is a trade name we own. We own the related design marks, and other trademarks on the Website. Page headers, custom graphics, button icons, and scripts are trademarks or trade dress we own. You may not use any of these trademarks, trade dress, or trade names without our express written permission.</p>
                    <p id="third-party">7. <strong>Third-Party Websites.</strong></p>
                    <p>VirtusNutra.com may contain links to other websites on the Internet that are owned and operated by third parties. We do not control the information, products, or services available on these third party websites. The inclusion of any link does not imply our endorsement of the applicable website or any association with the website’s operators. Because we have no control over such websites and resources, you agree that we are not responsible or liable for the availability or the operation of such external websites, for any material located on or available from any such websites, or for the protection of your data privacy by third parties. Any dealings with, or participation in promotions offered by, advertisers on the Website, including the payment and delivery of related goods or services, and any other terms, conditions, warranties, or representations associated with such dealings or promotions, are solely between you and the applicable advertiser or other third party. You further agree that we shall not be responsible or liable, directly or indirectly, for any loss or damage caused by the use of or reliance on any such material available on or through any such website, or any such dealings or promotions. Notwithstanding anything in this TOS to the contrary, this section does not apply in the state of New Jersey.</p>
                    <p id="linking-framing">8. <strong>Linking and Framing.</strong></p>
                    <p>You may not deep link to portions of the Website, or frame, inline link, or similarly display any of our property, including, without limitation, the Website. You may not use any of our logos or other trademarks as part of a link without express written permission.</p>
                    <p id="comments">9. <strong>Comments.</strong></p>
                    <p>All comments, feedback, suggestions, ideas, and other submissions that you disclose, submit, or offer to us in connection with your use of the Website will become our exclusive property. Such disclosure, submission, or offer of any comments shall constitute an assignment to us of all worldwide right, title, and interest in all patent, copyright, trademark, and all other intellectual property and other rights whatsoever in and to the comments, and a waiver of any claim based on moral rights, unfair competition, breach of implied contract, breach of confidentiality, and any other legal theory. You will, at our cost, execute any documents to effect, record, or perfect such assignment. Thus, we will own exclusively all such right, title, and interest, and shall not be limited in any way in the use, commercial or otherwise, of any comments. You should not submit any comments to us if you do not wish to assign such rights to us. We are and will be under no obligation to: (i) maintain any comments in confidence; (ii) pay to you or any third party any compensation for any comments; or (iii) respond to any comments. You are and shall remain solely responsible for the content of any comments you make.</p>
                    <p id="indemnification">10. <strong>Indemnification.</strong></p>
                    <p>You agree to defend, indemnify, and hold the Website and its subsidiaries, affiliates, and their directors, officers, agents, members, shareholders, co-branders, or other partners, employees, and advertising partners harmless from any liabilities, losses, actions, damages, claims, or demands, including reasonable attorneys’ fees, costs, and expenses, made by any third party directly or indirectly relating to or arising out of (a) content you provide to the Website or otherwise transmit or obtain through the Service, (b) your use of the Service, (c) your connection to the Service, (d) your violation of this Agreement, (e) your violation of any rights of another, or (f) your failure to perform your obligations hereunder. If you are obligated to provide indemnification pursuant to this provision, we may, in our sole and absolute discretion, control the disposition of any claim at your sole cost and expense. Without limitation of the foregoing, you may not settle, compromise, or in any other manner dispose of any claim without our consent. NOTWITHSTANDING ANYTHING IN THIS TOS TO THE CONTRARY, THIS SECTION DOES NOT APPLY IN NEW JERSEY.</p>
                    <p id="disclaimers-exclusions-limitations">11. <strong>DISCLAIMERS, EXCLUSIONS AND LIMITATIONS.</strong></p>
                    <p>(a) DISCLAIMER OF WARRANTIES. WE PROVIDE THE WEBSITE, THE PRODUCTS, AND SERVICES ON AN "AS IS" AND "AS AVAILABLE" BASIS. WE DO NOT REPRESENT OR WARRANT THAT THE PRODUCTS, THE WEBSITE, THE SERVICES, THEIR USE, AND ANY INFORMATION ON CONTAINED THEREIN: (I) WILL BE UNINTERRUPTED OR SECURE, (II) WILL BE FREE OF DEFECTS, INACCURACIES, OR ERRORS, (III) WILL MEET YOUR REQUIREMENTS, OR (IV) WILL OPERATE IN THE CONFIGURATION OF OR WITH OTHER HARDWARE OR SOFTWARE YOU USE. WE MAKE NO WARRANTIES OTHER THAN THOSE MADE EXPRESSLY IN THIS TOS, AND HEREBY DISCLAIM ANY AND ALL IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE OR CAUSE, MERCHANTABILITY, AND NON-INFRINGEMENT.</p>
                    <p>(b) DISCLAIMER OF FORWARD-LOOKING STATEMENTS. THIS WEBSITE MAY CONTAIN FORWARD-LOOKING STATEMENTS THAT REFLECT OUR CURRENT EXPECTATION REGARDING FUTURE EVENTS AND BUSINESS DEVELOPMENT. THE FORWARD-LOOKING STATEMENTS INVOLVE RISKS AND UNCERTAINTIES. ACTUAL DEVELOPMENTS OR RESULTS COULD DIFFER MATERIALLY FROM THOSE PROJECTED AND DEPEND ON A NUMBER OF FACTORS, SOME OF WHICH ARE OUTSIDE OUR CONTROL.</p>
                    <p>(c) HEALTH-RELATED INFORMATION. WE PROVIDE INFORMATION ON THE WEBSITE FOR INFORMATIONAL PURPOSES ONLY. IT IS NOT MEANT AS A SUBSTITUTE FOR THE ADVICE OF A DOCTOR OR OTHER HEALTHCARE PROFESSIONAL. YOU SHOULD NOT USE THE INFORMATION AVAILABLE ON OR THROUGH THE WEBSITE FOR DIAGNOSING OR TREATING A MEDICAL CONDITION. YOU SHOULD CAREFULLY READ ALL PRODUCT INSTRUCTIONS PRIOR TO USE.</p>
                    <p>(d) PRODUCTS. ALL PRODUCTS ARE SUBJECT ONLY TO ANY APPLICABLE WARRANTIES OF THEIR RESPECTIVE MANUFACTURERS, DISTRIBUTORS, AND SUPPLIERS, IF ANY, PROVIDED IN THE PRODUCT PACKAGING. TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW, WE HEREBY DISCLAIM ALL WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, OR FITNESS FOR A PARTICULAR PURPOSE OR CAUSE. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, WE HEREBY EXPRESSLY DISCLAIM ALL LIABILITY FOR PRODUCT DEFECT OR FAILURE, CLAIMS THAT ARE DUE TO NORMAL WEAR, PRODUCT MISUSE, ABUSE, PRODUCT MODIFICATION, IMPROPER PRODUCT SELECTION, NONCOMPLIANCE WITH ANY CODES, OR MISAPPROPRIATION.</p>
                    <p>(e) EXCLUSION OF DAMAGES. WE WILL NOT BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY CONSEQUENTIAL, INCIDENTAL, INDIRECT, PUNITIVE, OR SPECIAL DAMAGES (INCLUDING, WITHOUT LIMITATION, DAMAGES RELATING TO LOST PROFITS, LOST DATA, OR LOSS OF GOODWILL) ARISING OUT OF, RELATING TO, OR CONNECTED WITH THE USE OF THE WEBSITE OR PRODUCTS, REGARDLESS OF THE CAUSE OF ACTION ON WHICH THEY ARE BASED, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OCCURRING.</p>
                    <p>(f) LIMITATION OF LIABILITY. IN NO EVENT WILL OUR AGGREGATE LIABILITY ARISING FROM, RELATING TO, OR IN CONNECTION WITH THIS TOS, INCLUDING, WITHOUT LIMITATION, CLAIMS RELATING TO THE WEBSITE OR THE PRODUCTS, EXCEED THE GREATER OF $100 OR THE AMOUNT THAT YOU PAID FOR THE PRODUCTS. NOTWITHSTANDING ANYTHING IN THIS TOS TO THE CONTRARY, THIS DISCLAIMER OF WARRANTY, EXCLUSIONS, AND LIMITATIONS DO NOT APPLY IN NEW JERSEY.</p>
                    <p id="force-majeure">12. <strong>Force Majeure.</strong></p>
                    <p>You acknowledge and understand that if the Website is unable to provide the Products as a result of a force majeure event, the Website will not be in breach of any of its obligations toward you under these TOS. A force majeure event means any event beyond the control of the Website. THE WEBSITE SHALL NOT HAVE ANY LIABILITY TO YOU, WHETHER IN CONTRACT, WARRANTY, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER FORM OF LIABILITY FOR FAILING TO PERFORM ITS OBLIGATIONS UNDER THIS AGREEMENT TO THE EXTENT THAT SUCH FAILURE IS AS A RESULT OF A FORCE MAJEURE EVENT. THIS SECTION SHALL NOT APPLY IN THE STATE OF NEW JERSEY.</p>
                    <p id="domestic-use-export-restrictions">13. <strong>Domestic Use and Export Restriction.</strong></p>
                    <p>We control the Website from our offices within the United States of America. We make no representation that the Website or its content (including, without limitation, any products or services available on or through the Website) are appropriate or available for use in other locations. Users who access the Website from outside the United States of America do so on their own initiative and must bear all responsibility for compliance with local laws, if applicable. Further, the United States export control laws prohibit the export of certain technical data and software to certain territories. No content from the Website may be downloaded in violation of United States law.</p>
                    <p id="arbitration">14. <strong>Arbitration and Waiver of Class Action Rights.</strong></p>
                    <p>This TOS and any issue or dispute arising out of or otherwise related to this TOS or your use of our Website, the <a href="/privacy"> Privacy Policy</a>, or any matter concerning Virtus Nutra including use and purchase of any product and enrollment in the VIP Membership Program, collectively "Disputes," shall be governed exclusively by the laws of the Commonwealth of Massachusetts, excluding its conflict of law provisions.
                        If a Dispute arises, we agree to first contact each other with a written description of the Dispute, all relevant documents and information, and the proposed resolution. You agree to contact us with Disputes by writing to us at Virtus Nutra, 105 Commerce Dr, Aston, PA 19014. Virtus Nutra will contact you by letter to the billing address you provided us.</p>
                    <p>If any Dispute cannot be resolved informally, we each agree that any and all Disputes, other than those filed in small claims court, shall be submitted to final and binding arbitration before a single arbitrator of the American Arbitration Association ("AAA") in a location convenient to you. Either party may commence the arbitration process by submitting a written demand for arbitration with the AAA, and providing a copy to the other party. The arbitration will be conducted in accordance with the provisions of the AAA’s Commercial Dispute Resolutions Procedures, Supplementary Procedures for Consumer-Related Disputes, in effect at the time of submission of the demand for arbitration. We will pay all of the filing costs, including arbitrator fees. Judgment on the award rendered by the arbitrator may be entered in any court of competent jurisdiction. Notwithstanding the foregoing, the following shall not be subject to arbitration and may be adjudicated only in the state and federal courts of Massachusetts: (i) any dispute, controversy, or claim relating to or contesting the validity of the our proprietary rights, including without limitation, trademarks, service marks, copyrights, or trade secrets; or (ii) an action by a party for temporary, preliminary, or permanent injunctive relief, whether prohibitive or mandatory, or other provisional relief. <strong>You expressly agree to refrain from bringing or joining any claims in any representative or class-wide capacity, including but not limited to bringing or joining any claims in any class action or any class-wide arbitration.</strong></p>
                    <p><strong>YOU UNDERSTAND THAT YOU WOULD HAVE HAD A RIGHT TO LITIGATE THROUGH A COURT, TO HAVE A JUDGE OR JURY DECIDE YOUR CASE, AND TO BE PARTY TO A CLASS OR REPRESENTATIVE ACTION. HOWEVER, YOU UNDERSTAND AND CHOOSE TO HAVE ANY CLAIMS DECIDED INDIVIDUALLY AND ONLY THROUGH ARBITRATION.</strong></p>
                    <p id="modification-of-terms">15. <strong>Modification of Terms of Service.</strong></p>
                    <p>We reserve the right to change or modify these TOS at any time, with or without notice, and your continued use of the Website will be conditioned upon the TOS in force at the time of your use. You can always check the most current version of the TOS at this page.</p>
                    <p id="termination">16. <strong>Termination.</strong></p>
                    <p>We maintain the right to terminate your access to the Website if we reasonably believe you have breached any of the TOS. Following termination, you will not be permitted to use the Website and we may, in our sole discretion, cancel any outstanding Product orders. If your access to the Website is terminated, we reserve the right to exercise whatever means we deem necessary to prevent unauthorized access to the Website, including, but not limited to, technological barriers, IP mapping, and direct contact with your Internet Service Provider. This TOS will survive indefinitely unless and until we choose to terminate it, with or without notice, regardless of whether any account or order you open is terminated by you or us, or if you have the right to access or use the Website.</p>
                    <p id="integration">17. <strong>Integration.</strong></p>
                    <p>This TOS contains the entire understanding between you and us regarding the use of the Website, and supersedes all prior and contemporaneous agreements and understandings between you and us relating thereto.</p>
                    <p id="additional-terms">18. <strong>Additional Terms.</strong></p>
                    <p>These TOS, and all of your rights and obligations under them, may not be assigned or transferred by you without our prior written consent. No failure or delay by a party in exercising any right, power, or privilege under this TOS will operate as a waiver thereof, nor will any single or partial exercise of any right, power, or privilege preclude any other or further exercise thereof, or the exercise of any other right, power, or privilege under this TOS. You are an independent contractor, and no agency, partnership, joint venture, or employee-employer relationship is intended or created by this TOS. The invalidity or unenforceability of any provision of this TOS will not affect the validity or enforceability of any other provision of this TOS, all of which will remain in full force and effect.</p>
                </div>
            </section>
            <section class="connection wrapper">
                <div class="customer-service"> <img src="images/56eebc.png">
                    <p>Customer Service</p>
                    <a href="/contact-us">Contact</a> </div>
                <div class="follow-us">
                    <div class="sm icon-wrap"> <a href="#" target="_blank"><img src="images/5f58ea.png" class="sm-icon"></a> <a href="#" target="_blank"><img src="images/8b636a.png" class="sm-icon"></a> <a href="#" target="_blank"><img src="images/70f467.png" class="sm-icon"></a> <a href="#" target="_blank"><img src="images/266418.png" class="sm-icon"></a> </div>
                    <p>Follow Us &amp; Stay In The Know</p>
                </div>
            </section>
            <section class="retailers wrapper">
                <div class="retail-txt">
                    <p>Find <strong>Virtus Nutra</strong> at These Retailers</p>
                </div>
                <div class="retail-imgs"> <img src="images/3d6ea2.png" class="retail-img"> <img src="images/0aad6b.png" class="retail-img"> <img src="images/edef61.png" class="retail-img"> <img src="images/70cba2.png" class="retail-img"> <img src="images/4dbe94.png" class="retail-img"> <img src="images/33a8fb.png" class="retail-img"> <img src="images/d749d7.png" class="retail-img"> <img src="images/61f381.png" class="retail-img"> <img src="images/a44784.png" class="retail-img"> <img src="images/ba94fc.png" class="retail-img"> <img src="images/d5120c.png" class="retail-img"> </div>
            </section>
            <?php include('footer.php') ?>
        </div>
        <script type="text/javascript" src="js/global.js"></script> 
        <script type="text/javascript" src="js/site_page-52.js"></script> 

        <!-- Content for Snippet Type Other --> 
        <script type="text/javascript">
            var link = document.createElement('link');
            link.href = "https://fonts.googleapis.com/css?family=Lato:400,700";
            link.rel = "stylesheet";
            document.getElementsByTagName('head')[0].appendChild(link);
            // <link href="https://fonts.googleapis.com/css?family=Lato:400,700" rel="stylesheet">
        </script>
        <div id="nc-pixel-container-footer"> </div>
        <script type="text/javascript">window.NREUM || (NREUM = {});NREUM.info = {"beacon": "bam.nr-data.net", "licenseKey": "caac70a4fe", "applicationID": "554941,554934,554935", "transactionName": "NQBbZxADD0pVAkwMCgxKeFAWCw5XGwVdAwQXCU0cCwwFXExOSwwRBw==", "queueTime": 0, "applicationTime": 69, "atts": "GUdYEVgZHEQ=", "errorBeacon": "bam.nr-data.net", "agent": ""}</script>
    </body>
</html>
